<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-30 13:00

=======
# Generated by Django 5.2.1 on 2025-05-24 15:46

import django.db.models.deletion
>>>>>>> 7cb7e58 (clothmate added)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='BankAd',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_img', models.ImageField(null=True, upload_to='bankad/')),
            ],
            options={
                'db_table': 'bankad_table',
=======
            name='ClothType',
            fields=[
                ('cloth_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth_type', models.CharField(max_length=100)),
                ('cloth_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cloth_type',
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('dress_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.clothtype')),
            ],
            options={
                'db_table': 'dress',
>>>>>>> 7cb7e58 (clothmate added)
            },
        ),
    ]
