# Generated by Django 5.2.1 on 2025-05-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAd',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_img', models.ImageField(null=True, upload_to='bankad/')),
            ],
            options={
                'db_table': 'bankad_table',
            },
        ),
    ]
