# Generated by Django 5.2.1 on 2025-05-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='cloth',
        ),
        migrations.DeleteModel(
            name='ClothType',
        ),
        migrations.DeleteModel(
            name='Dress',
        ),
    ]
