# Generated by Django 5.2.1 on 2025-05-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_remove_dress_cloth_delete_clothtype_delete_dress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('cloth_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth_type', models.CharField(max_length=100)),
                ('cloth_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cloth_type',
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('dress_id', models.AutoField(primary_key=True, serialize=False)),
                ('dress_name', models.CharField(max_length=100)),
                ('dress_arrival', models.CharField(max_length=20)),
                ('dress_img', models.ImageField(blank=True, null=True, upload_to='dressimg/')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.clothtype')),
            ],
            options={
                'db_table': 'dress',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dress')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
