<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-31 13:03
=======
# Generated by Django 5.2.1 on 2025-05-24 17:58
>>>>>>> 7cb7e58 (clothmate added)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('app1', '0009_remove_userclass_acc_type_delete_bankad_and_more'),
=======
        ('app1', '0009_remove_category_dress_remove_clothtype_dress_and_more'),
>>>>>>> 7cb7e58 (clothmate added)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='AccountType',
            fields=[
                ('acc_type', models.AutoField(primary_key=True, serialize=False)),
                ('acc_name', models.CharField(max_length=100)),
                ('min_balance', models.IntegerField()),
            ],
            options={
                'db_table': 'acc_table',
            },
        ),
        migrations.CreateModel(
            name='BankAd',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_img', models.ImageField(null=True, upload_to='bankad/')),
            ],
            options={
                'db_table': 'bankad_table',
            },
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_sex', models.CharField(max_length=10)),
                ('user_dob', models.DateField()),
                ('user_age', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_mobile', models.BigIntegerField()),
                ('user_address', models.CharField(max_length=100)),
                ('user_city', models.CharField(max_length=20)),
                ('user_state', models.CharField(max_length=20)),
                ('user_country', models.CharField(max_length=10)),
                ('user_pincode', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('user_balance', models.IntegerField()),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.accounttype')),
            ],
            options={
                'db_table': 'user_table',
=======
            name='Dress',
            fields=[
                ('dress_id', models.AutoField(primary_key=True, serialize=False)),
                ('dress_name', models.CharField(max_length=100)),
                ('dress_arrival', models.DateField(max_length=20)),
                ('dress_price', models.IntegerField()),
                ('dress_img', models.ImageField(blank=True, null=True, upload_to='dressimg/')),
            ],
            options={
                'db_table': 'dress',
            },
        ),
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('cloth_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth_type', models.CharField(max_length=100)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dress')),
            ],
            options={
                'db_table': 'cloth_type',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dress')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dress')),
            ],
            options={
                'db_table': 'cart',
>>>>>>> 7cb7e58 (clothmate added)
            },
        ),
    ]
