# Generated by Django 5.2.1 on 2025-05-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dress',
        ),
        migrations.RemoveField(
            model_name='clothtype',
            name='dress',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ClothType',
        ),
        migrations.DeleteModel(
            name='Dress',
        ),
    ]
