# Generated by Django 5.2.1 on 2025-05-31 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0011_remove_userclass_acc_type_delete_bankad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('acc_type', models.AutoField(primary_key=True, serialize=False)),
                ('acc_name', models.CharField(max_length=100)),
                ('min_balance', models.IntegerField()),
            ],
            options={
                'db_table': 'acc_table',
            },
        ),
        migrations.CreateModel(
            name='BankAd',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_img', models.ImageField(null=True, upload_to='bankad/')),
            ],
            options={
                'db_table': 'bankad_table',
            },
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_sex', models.CharField(max_length=10)),
                ('user_dob', models.DateField()),
                ('user_age', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_mobile', models.BigIntegerField()),
                ('user_address', models.CharField(max_length=100)),
                ('user_city', models.CharField(max_length=20)),
                ('user_state', models.CharField(max_length=20)),
                ('user_country', models.CharField(max_length=10)),
                ('user_pincode', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('user_balance', models.IntegerField()),
                ('user_password', models.CharField(max_length=10)),
                ('acc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.accounttype')),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
