# Generated by Django 5.2.1 on 2025-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='user_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
