# Generated by Django 5.2.1 on 2025-05-25 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCat',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=200)),
                ('cloth_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.clothtype')),
            ],
            options={
                'db_table': 'category_table',
            },
        ),
    ]
