# Generated by Django 5.2.1 on 2025-06-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_userclass_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclass',
            name='acc_type',
        ),
        migrations.DeleteModel(
            name='BankAd',
        ),
        migrations.DeleteModel(
            name='AccountType',
        ),
        migrations.DeleteModel(
            name='UserClass',
        ),
    ]
