# Generated by Django 5.2.1 on 2025-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_typecat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecat',
            name='cat_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
