# Generated by Django 5.2.1 on 2025-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_typecat_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='gender_img',
            field=models.ImageField(null=True, upload_to='genderimg/'),
        ),
    ]
