# Generated by Django 5.2.1 on 2025-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_gender_gender_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothtype',
            name='cloth_type_img',
            field=models.ImageField(null=True, upload_to='clothtypeimg/'),
        ),
    ]
