# Generated by Django 5.2.1 on 2025-05-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_clothtype_cloth_type_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='gender_card_img',
            field=models.ImageField(blank=True, null=True, upload_to='genderimg/'),
        ),
    ]
