# Generated by Django 5.2.1 on 2025-05-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_gender_gender_card_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='gender_img',
            new_name='gender_carousal_img',
        ),
    ]
