# Generated by Django 5.2.1 on 2025-06-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
