# Generated by Django 5.2.1 on 2025-06-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_userclass_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='user_balance',
            field=models.IntegerField(default=0),
        ),
    ]
