# Generated by Django 5.2.1 on 2025-06-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
